import { useState, useEffect } from "react";
import { jsPDF } from "jspdf";
import SideBar from "./components/SideBar";
import Upload from "./components/Upload";
import Analysis from "./components/Analysis";
import AiSuggestions from "./components/AiSuggestions";
import History from "./components/History";

function App() {

  const [file, setFile] = useState(null);
  const [resumeText, setResumeText] = useState("");
  const [skills, setSkills] = useState([]);
  const [jobDescription, setJobDescription] = useState("");
  const [history, sethistory] = useState([])
  const [suggestions, setSuggestions] = useState("")
  const [analysis, setAnalysis] = useState(null)
  const [loading, setLoading] = useState(false)
  const [sidebarOpen, setSidebarOpen]=useState(false)


  useEffect(() => {
    fetchHistory();
  }, []);

  const fetchHistory = async () => {
    const response = await fetch("https://my-resume-scan-ai-based-resume-analyzer.onrender.com//history");
    const data = await response.json();
    sethistory(data.history);
  };

  const handleUpload = async () => {
    setLoading(true);

    try {

      if (!file) {
        alert("Please upload a resume");
        return;
      }

      if (!jobDescription) {
        alert("Please enter job description");
        return;
      }
      const formData = new FormData();
      formData.append("resume", file);
      formData.append("jobDescription", jobDescription);

      const response = await fetch("https://my-resume-scan-ai-based-resume-analyzer.onrender.com/upload", {
        method: "POST",
        body: formData,
      });

      const data = await response.json();

      setSuggestions(data.feedback)
      setAnalysis(data)
      fetchHistory()
    }
    catch (error) {
      console.log(error)
      alert("Something went wrong. Please Try Again")
    }
    finally {
      setLoading(false)
    }
  };

  const downloadReport = () => {
    const doc = new jsPDF();
    doc.setFontSize(24);
    doc.setTextColor(0, 62, 199);
    doc.text("AI Resume Analysis Report", 20, 25);
    doc.setDrawColor(220);
    doc.line(20, 32, 190, 32);
    doc.setFontSize(18);
    doc.setTextColor(0, 0, 0);
    doc.text(`ATS Score: ${analysis?.ats_score}%`, 20, 50);
    doc.setFontSize(16);
    doc.text("Score Breakdown", 20, 70);
    doc.setFontSize(13);
    doc.text(`Keyword Match: ${analysis?.keywords_score}%`, 25, 82);
    doc.text(`Semantic Match: ${analysis?.semantic_score}%`, 25, 92);
    doc.text(`Formatting Score: ${analysis?.formatting_score}%`, 25, 102);
    doc.text(`Resume Quality: ${analysis?.quality_score}%`, 25, 112);
    doc.setFontSize(16);
    doc.text("Missing Skills", 20, 132);
    doc.setFontSize(13);
    let skillY = 144;
    analysis?.missing_skills?.forEach((skill) => {
      doc.text(`• ${skill}`, 25, skillY);
      skillY += 10;
    });
    doc.setFontSize(16);
    doc.text("AI Suggestions", 20, skillY + 10);
    doc.setFontSize(13);
    const suggestionLines = doc.splitTextToSize(suggestions || "", 160);
    doc.text(suggestionLines, 25, skillY + 22);
    doc.setFontSize(11);
    doc.setTextColor(120);
    doc.text("Generated by AI Resume Analyzer", 20, 285);
    doc.save("ATS_Report.pdf");
  };

  return (
    <div className="min-h-screen w-full flex overflow-x-hidden bg-[#F7F9FF]">
      <SideBar sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen}/>
      <button onClick={()=>setSidebarOpen(true)} className={`fixed top-1 left-1 z-50 bg-blue-600 text-white p-2 rounded-xl shadow-lg md:hidden ${sidebarOpen?"hidden":"block"}`}> 
          ☰
      </button>


      <div className="flex flex-col p-3 md:p-5 w-full gap-5">
          
        <div className="w-full h-full items-center justify-center lg:items-start flex flex-col lg:flex-row gap-5 mt-5 ">
          <div className="lg:flex-[2.2] w-full flex flex-col gap-5">

            <div className="w-full min-h-120 border-gray-200 border-2 shadow-xl">
              <Upload file={file} setFile={setFile} jobDescription={jobDescription} setJobDescription={setJobDescription} handleUpload={handleUpload} loading={loading} />
            </div>

            <div className="w-full border-gray-200 border-2 shadow-xl">
              <p className="font-bold text-2xl pt-3 pl-3 ">AI-Powered Suggestions</p>
              <AiSuggestions suggestions={suggestions} />
            </div>

          </div>
          <div className="lg:flex-1 w-full min-w-0 border-gray-200 border-2 shadow-xl bg-white">
            <Analysis analysis={analysis} downloadReport={downloadReport} />
          </div>
        </div>

        <div className=" border-gray-200 border-2 shadow-xl pt-5 pl-5 bg-white mb-5">

          <p className="font-bold text-2xl" >History</p>
          <History history={history} />

        </div>
      </div>
    </div>
  );
}

export default App;



//  <button
//           onClick={downloadReport}
//           className="bg-blue-600 text-white px-6 py-2 rounded"
//         >
//           Download Report
//         </button>